---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Values.app }}
  name: {{ .Values.app }}-env
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  EMBEDDING_MAP_PATH: "{{ .Values.workingDir }}/embedding_map.json"
  EMBEDDINGS_DEFAULT_MODEL: "{{ .Values.embeddingsDefaultModel }}"
---
# Secret for embedding map json
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app }}-files
  namespace: {{ .Values.namespace }}
stringData:
  embedding_map.json: |
    {
    {{- if .Values.embeddings }}
    {{- range $index, $embedding := .Values.embeddings }}
      "{{ $embedding.name }}": {
        "url": "{{ $embedding.url }}",
        "model": "{{ $embedding.model }}",
        "api_key": "{{ $embedding.api_key }}"
      }{{ if ne (add $index 1) (len $.Values.embeddings) }},{{ end }}
    {{- end }}
    {{- end }}
    }